apiVersion: v1
kind: ConfigMap

metadata:
  name: petclinic-config
  namespace: {{ .Release.Namespace }}

data:
  SPRING_PROFILES_ACTIVE: mysql
  SPRING_DATASOURCE_URL: jdbc:mysql://demo-db:3306/petclinic