apiVersion: v1
kind: ConfigMap

metadata:
  name: petclinic-config
  namespace: {{ .Values.namespace }}

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.database.url | quote }}