apiVersion: v1
kind: ConfigMap

metadata:
  name: petclinic-config
  namespace: {{ .Values.namespace }}

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE }}
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}