---
apiVersion: v1
kind: Secret

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  username: "{{ .Values.database.username }}"
  password: "{{ .Values.database.password }}"
  database: "{{ .Values.database.database }}"

---
apiVersion: v1
kind: Service

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}

spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-db

  template:
    metadata:
      labels:
        app: demo-db

    spec:
      containers:
        - name: mysql

          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: database

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password

          ports:
            - containerPort: 3306

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15