---
apiVersion: v1
kind: Secret

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}

type: servicebinding.io/postgresql

stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "{{ .Values.database.host }}"
  port: "{{ .Values.database.port }}"
  database: "{{ .Values.database.name }}"
  username: "{{ .Values.secret.username }}"
  password: "{{ .Values.secret.password }}"

---
apiVersion: v1
kind: Service

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}

spec:
  ports:
    - port: {{ .Values.database.port }}
  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-db
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-db

  template:
    metadata:
      labels:
        app: demo-db

    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: database

          ports:
            - containerPort: {{ .Values.database.port }}
              name: postgresql

          livenessProbe:
            tcpSocket:
              port: postgresql

          readinessProbe:
            tcpSocket:
              port: postgresql

          startupProbe:
            tcpSocket:
              port: postgresql