apiVersion: v1
kind: Secret

metadata:
  name: petclinic-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.password }}