replicaCount: 1

namespace: petclinic

image:
  repository: acrkalyani.azurecr.io/spring-petclinic
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

database:
  host: demo-db
  port: 5432
  name: petclinic

  image:
    repository: postgres
    tag: "18.4"

config:
  SPRING_PROFILES_ACTIVE: postgres

secret:
  username: postgres
  password: postgres