namespace: petclinic

replicaCount: 1

image:
  repository: containeregistery.azurecr.io/spring-petclinic
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

secret:
  username: petclinic
  password: petclinic

config:
  SPRING_PROFILES_ACTIVE: mysql

database:
  image:
    repository: mysql
    tag: "8.0"

  service:
    port: 3306

  containerPort: 3306

  url: jdbc:mysql://demo-db:3306/petclinic

  username: petclinic
  password: petclinic
  database: petclinic

ingress:
  enabled: true
  className: nginx