trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDirectory: 'terraform'

stages:

#=====================================================
# Stage 1 - Terraform Validation & Plan
#=====================================================

- stage: TerraformPlan
  displayName: 'Terraform Validation and Plan'

  jobs:

  - job: TerraformValidation
    displayName: 'Terraform Init Validate Plan'

    steps:

    - checkout: self

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    # Verify Version
    - script: |
        terraform version
      displayName: 'Verify Terraform Version'

    # Format Check
    - script: |
        cd $(terraformWorkingDirectory)
        terraform fmt -check
      displayName: 'Terraform Format'

    # Terraform Init
    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: 'project-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformWorkingDirectory)
          terraform init

    # Terraform Validate
    - task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
        azureSubscription: 'project-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformWorkingDirectory)
          terraform validate

    # Terraform Plan
    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: 'project-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformWorkingDirectory)

          terraform plan \
          -var-file="terraform.tfvars" \
          -out=tfplan

    # Publish Plan
    - publish: $(terraformWorkingDirectory)/tfplan
      artifact: terraform-plan
      displayName: 'Publish Terraform Plan'


#=====================================================
# Stage 2 - Terraform Apply
#=====================================================

#- stage: TerraformApply
#  displayName: 'Terraform Apply'
#  dependsOn: TerraformPlan
#  condition: succeeded()

#  jobs:

#  - deployment: TerraformDeployment
#    displayName: 'Terraform Infrastructure Deployment'

#    environment: terraform-dev

#    strategy:
#      runOnce:
#        deploy:

#          steps:

#          - checkout: self

          # IMPORTANT:
          # Install Terraform AGAIN because this is a new job

#          - task: TerraformInstaller@1
#            displayName: 'Install Terraform'
#            inputs:
#              terraformVersion: 'latest'

#          - script: |
#              terraform version
#            displayName: 'Verify Terraform Version'

#         - task: AzureCLI@2
#            displayName: 'Terraform Init'
#            inputs:
#              azureSubscription: 'project-connection'
#              scriptType: bash
#              scriptLocation: inlineScript
#              inlineScript: |
#                cd $(terraformWorkingDirectory)
#                terraform init
#
#          - task: AzureCLI@2
#            displayName: 'Terraform Apply'
#            inputs:
#              azureSubscription: 'project-connection'
#             scriptType: bash
#              scriptLocation: inlineScript
#              inlineScript: |
#                cd $(terraformWorkingDirectory)

#                terraform apply \
#                -auto-approve \
#                -var-file="terraform.tfvars"