apiVersion: apps/v1
kind: Deployment

metadata:
  name: petclinic

spec:
  replicas: 1

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:

      containers:
      - name: petclinic

        image: petclinicacr.azurecr.io/petclinic:latest

        ports:
        - containerPort: 8080

        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true

      volumes:
      - name: secrets-store

        csi:
          driver: secrets-store.csi.k8s.io

          readOnly: true

          volumeAttributes:
            secretProviderClass: "azure-keyvault"