apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault

spec:
  provider: azure

  parameters:

    usePodIdentity: "false"

    useVMManagedIdentity: "true"

    userAssignedIdentityID: "9335f854-c7f5-49d1-9ea5-6f12c8ad9aff"

    tenantId: "d3d2849e-4c93-44b5-aad8-d78ca7a3c53b"

    objects: |
      array:
        - |
          objectName: db-username
          objectType: secret

        - |
          objectName: db-password
          objectType: secret

        - |
          objectName: acr-username
          objectType: secret

        - |
          objectName: acr-password
          objectType: secret