apiVersion: apps/v1
kind: Deployment

metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic

spec:
  replicas: 1

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      containers:
      - name: petclinic
        image: acrkalyani.azurecr.io/spring-petclinic:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: petclinic-config
              key: SPRING_PROFILES_ACTIVE

        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: petclinic-config
              key: SPRING_DATASOURCE_URL

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: SPRING_DATASOURCE_USERNAME

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: SPRING_DATASOURCE_PASSWORD

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3