trigger:
  branches:
    include:
      - feature/centralized-logging

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SONAR-CONFIG

- name: JAVA_VERSION
  value: '21'

- name: imageRepository
  value: 'spring-petclinic'

- name: dockerfilePath
  value: 'Dockerfile'

- name: imageTag
  value: '$(Build.BuildId)'

steps:

# Checkout source
- checkout: self

# Install Java 21
- task: JavaToolInstaller@0
  displayName: 'Install Java 21'
  inputs:
    versionSpec: '$(JAVA_VERSION)'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Prepare SonarCloud
- task: SonarCloudPrepare@3
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarCloud: 'new-connection'
    organization: '$(SONAR_ORG)'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=$(SONAR_PROJECT)
      sonar.organization=$(SONAR_ORG)

# Build + Test + Sonar Analysis
- task: Maven@4
  displayName: 'Build, Test and Analyze'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    mavenVersionOption: 'Default'

# Publish Quality Gate
#- task: SonarCloudPublish@3
#  displayName: 'Publish SonarCloud Quality Gate'
#  inputs:
#    pollingTimeoutSec: '300'

# Publish Build Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'petclinic'
    publishLocation: 'Container'

# Build and Push Docker Image
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'acr-docker-connection'
    repository: '$(imageRepository)'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(imageTag)
      latest